# Generated by Selenium IDE
import time
from selenium import webdriver
import pytest
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains

from application import Application
from group import Group

@pytest.fixture
def app(request):
    fixture = Application()
    request.addfinalizer(fixture.destroy)
    return fixture

# class TestEmailtest():
#     def setup_method(self, method):
#         self.app = Application()
#         self.driver = webdriver.Chrome()
#         self.vars = {}
#
#     def teardown_method(self, method):
#         self.app.destroy()

def test_emailtest(app):
    app.login("testpython1111@gmail.com", "testpython")
    app.send_email(Group("Hello"))
    app.logout()
    app.driver.close()

def test_emailtest_2(app):
    app.login("testpython1111@gmail.com", "testpython")
    app.send_email(Group("World"))
    app.logout()
    app.driver.close()
