# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestNewtest():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_newtest(self):
    self.driver.get("https://www.google.com.ua/")
    self.driver.set_window_size(1552, 840)
    self.driver.find_element(By.ID, "gb_70").click()
    self.driver.find_element(By.CSS_SELECTOR, ".JDAKTe:nth-child(1) .w1I7fb").click()
    self.driver.find_element(By.NAME, "password").click()
    self.driver.find_element(By.NAME, "password").send_keys("ruratestingjob")
    self.driver.find_element(By.CSS_SELECTOR, ".VfPpkd-LgbsSe-OWXEXe-k8QpJ > .VfPpkd-RLmnJb").click()
    self.driver.find_element(By.CSS_SELECTOR, ".gb_Ac").click()
    self.driver.switch_to.frame(1)
    self.driver.find_element(By.CSS_SELECTOR, ".u4RcUd > .j1ei8c:nth-child(6) .MrEfLc").click()
    self.driver.switch_to.default_content()
    self.driver.find_element(By.ID, ":2i").click()
    self.driver.find_element(By.CSS_SELECTOR, ".nX > .asa").click()
    self.driver.find_element(By.CSS_SELECTOR, ".gb_La").click()
    self.driver.find_element(By.ID, "gb_71").click()
  
