# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


class TestTest2():
    def setup_method(self, method):
        self.driver = webdriver.Chrome()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_test2(self):
        self.driver.get("https://www.google.com.ua/")
        self.driver.set_window_size(1936, 1056)
        self.driver.find_element(By.ID, "gb_70").click()
        self.driver.find_element(By.CSS_SELECTOR, ".JDAKTe:nth-child(3) .w1I7fb").click()
        element = self.driver.find_element(By.CSS_SELECTOR, ".ksBjEc > .VfPpkd-RLmnJb")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).perform()
        element = self.driver.find_element(By.CSS_SELECTOR, "body")
        actions = ActionChains(self.driver)
        actions.move_to_element(element, 0, 0).perform()
        self.driver.find_element(By.NAME, "password").send_keys("testpython")
        self.driver.find_element(By.CSS_SELECTOR, ".VfPpkd-LgbsSe-OWXEXe-k8QpJ > .VfPpkd-RLmnJb").click()
        element = self.driver.find_element(By.CSS_SELECTOR, ".VfPpkd-LgbsSe-OWXEXe-k8QpJ > .VfPpkd-RLmnJb")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).perform()
        element = self.driver.find_element(By.CSS_SELECTOR, "body")
        actions = ActionChains(self.driver)
        actions.move_to_element(element, 0, 0).perform()
        self.driver.find_element(By.LINK_TEXT, "Gmail").click()
        self.driver.find_element(By.CSS_SELECTOR, ".aHS-bnw").click()
        self.driver.find_element(By.LINK_TEXT, "Відкладені").click()
        self.driver.find_element(By.LINK_TEXT, "Надіслані").click()
        self.driver.find_element(By.LINK_TEXT, "Чернетки").click()
        self.driver.find_element(By.CSS_SELECTOR, ".gb_La").click()
        self.driver.find_element(By.ID, "gb_71").click()
